services:
  backend:
    build:
      context: ./backend
    container_name: vidaria-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vidaria
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=noelgats
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: vidaria-db
    environment:
      POSTGRES_DB: vidaria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: noelgats
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
