services:
  backend:
    build:
      context: ./backend
    container_name: vidaria-backend
    ports:
      - "8081:8081"
    env_file: 
      - .env  # Carga las variables desde el archivo .env
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}  # Perfil activo (por defecto 'default')
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: vidaria-db
    environment:
      POSTGRES_DB: vidaria
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}  # Desde el archivo .env
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: vidaria-redis
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
