# Nombre de la aplicación
spring.application.name=vidaria

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/vidaria
spring.datasource.username=postgres
spring.datasource.password=noelgats
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Formato SQL
spring.jpa.properties.hibernate.format_sql=true


# Configuración del servidor
server.port=8081

# Configuración de la API
tmdb.api.key=b519a2cc32b8654d1e683c286b4e8f4e
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
