spring.application.name=vidaria
spring.datasource.url=jdbc:postgresql://db:5432/vidaria
spring.datasource.username=postgres
spring.datasource.password=noelgats
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8081
tmdb.api.key=b519a2cc32b8654d1e683c286b4e8f4e
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.garmanaz.vidaria=INFO
logging.level.org.springframework=INFO
